### ISSUE TITLE
pods  is  pending

### ISSUE THREAD

**Issue by YYyp99** [BorisPolonsky/dify-helm#37] opened 2024-02-22 02:30 UTC
When I deploy in this way,dify-api,dipy-worker,postgresql-primary,postgresql-read,redis-master,redis-replicas,Their status is all pending，Error message display：0/3 nodes are available: 3 node(s) didn't find available persistent volumes to bind. preemption: 0/3 nodes are available: 3 Preemption is not helpful for scheduling..  ，All PVC states are pending
<img width="1172" alt="image" src="https://github.com/BorisPolonsky/dify-helm/assets/120240141/f6561280-8b9e-4baf-9bbf-486a6d9c93f8">
<img width="907" alt="image" src="https://github.com/BorisPolonsky/dify-helm/assets/120240141/6ba72397-a1ba-43c9-a367-3615e042b5cc">

**Comment by BorisPolonsky** [comment] 2024-02-22 12:13
What's the suggested reason of pending from `kubectl describe po`

**Comment by YYyp99** [comment] 2024-02-23 01:59
> Please provide reason that you pod got stuck in pending state (`kubectl describe po`) and the status of your `PV`/`PVC` (`kubectl describe pv`, `kubectl describe pvc`. It's likely that your node doesn't meet the requirement to create persistent volume as your `values.yaml` defined.

<img width="1182" alt="image" src="https://github.com/BorisPolonsky/dify-helm/assets/120240141/7bc7ebbc-2e13-446c-bd35-f95633661c27">
<img width="602" alt="image" src="https://github.com/BorisPolonsky/dify-helm/assets/120240141/ed6c6a9f-c881-4092-8e3e-ff01c3851e65">
<img width="1248" alt="image" src="https://github.com/BorisPolonsky/dify-helm/assets/120240141/84085ecf-7757-4a00-a662-ff78e8cf9560">
I created a new PV, but it seems like it's not being utilized.

**Comment by BorisPolonsky** [comment] 2024-02-25 10:11
> Please provide reason that you pod got stuck in pending state (`kubectl describe po`) and the status of your `PV`/`PVC` (`kubectl describe pv`, `kubectl describe pvc`. It's likely that your node doesn't meet the requirement to create persistent volume as your `values.yaml` defined.

<img width="1182" alt="image" src="https://github.com/BorisPolonsky/dify-helm/assets/120240141/7bc7ebbc-2e13-446c-bd35-f95633661c27">
<img width="602" alt="image" src="https://github.com/BorisPolonsky/dify-helm/assets/120240141/ed6c6a9f-c881-4092-8e3e-ff01c3851e65">
<img width="1248" alt="image" src="https://github.com/BorisPolonsky/dify-helm/assets/120240141/84085ecf-7757-4a00-a662-ff78e8cf9560">
I created a new PV, but it seems like it's not being utilized.

There's no need to create `pv` or `pvc` manually as they are all handled by this helm chart by design. What are the status of `pv` create by this helm chart as `kubectl describe pv -n <your-namespace>? What's the version of cluster and `helm`?

**Comment by YYyp99** [comment] 2024-02-26 01:38
> > I created a new PV, but it seems like it's not being utilized.
> 
> There's no need to create `pv` or `pvc` manually as they are all handled by this helm chart by design. What are the status of `PersistentVolumes` create by this helm chart as `kubectl describe pv -n <your-namespace>`? What's the version of the cluster and `helm`?

<img width="627" alt="image" src="https://github.com/BorisPolonsky/dify-helm/assets/120240141/a37b6a24-fc4e-468b-ac06-76203aa0bf5c">
This is a PV I created myself, Helm Chart did not create a PV，
<img width="1258" alt="image" src="https://github.com/BorisPolonsky/dify-helm/assets/120240141/fb3a9a90-aaab-444a-bd51-d157c09e8dd3">
the version of the cluster 
<img width="1084" alt="image" src="https://github.com/BorisPolonsky/dify-helm/assets/120240141/8115f81d-c1d0-4d12-9d9c-2beaa740981e">
the version of helm

**Comment by BorisPolonsky** [comment] 2024-02-26 03:30
@YYyp99 So you've manually created a `PersistentVolume` named `dify-postgresql-primary` in namespace `default` which is claimed by `redis-data-my-release-redis-master-0`. This suggests that:
- The dynamic provisioning feature works fine, which rules out possible causes describe [here](https://docs.bitnami.com/kubernetes/faq/troubleshooting/troubleshooting-persistence-volumes/)
- [bitnami/redis](https://github.com/bitnami/charts) failed to create a `PersistentVolume` as expected with your setup, and its `PVC` claims your manually created `PV` that were meant for `postgresql` with storage class `NFS`, which is not ideal for `redis`. You may need to specify storage class explicitly to prevent such cases.  (e.g. .Values.redis.master.persistence.storageClass)

We may need a copy of your `values.yaml` (with credentials redacted) and your start up command to rule out these two issues
- no `PersistentVolume` created
- `PVC` claims unexpected `PV`(wrong `PV` instance + wrong storage class

**Comment by YYyp99** [comment] 2024-02-26 07:56
> @YYyp99 So you've manually created a `PersistentVolume` named `dify-postgresql-primary` in namespace `default` which is claimed by `redis-data-my-release-redis-master-0`. This suggests that:
> 
> * The dynamic provisioning feature works fine, which rules out possible causes as `bitnami` described [here](https://docs.bitnami.com/kubernetes/faq/troubleshooting/troubleshooting-persistence-volumes/). (Component `redis` and `postgresql` are defined as dependency of [bitnami helm charts](https://github.com/bitnami/charts).)
> * [bitnami/redis](https://github.com/bitnami/charts/tree/main/bitnami/redis/templates) failed to create a `PersistentVolume` as expected with your setup, and its `PVC` claims your manually created `PV` that were meant for `postgresql` with storage class `NFS`, which is not ideal for `redis`. You may need to specify storage class explicitly to prevent such cases.  (e.g. `.Values.redis.master.persistence.storageClass`, `.Values.redis.replica.persistence.storageClass`, `api.persistence.persistentVolumeClaim.storageClass`)
> 
> We may need a copy of your `values.yaml` (with credentials redacted) and your start up command to identify the cause of two issues
> 
> * no `PersistentVolume` were created by this chart or `bitnami` depdendency
> * `PVC` claims unexpected `PV`(wrong `PV` instance + wrong storage class)
> 
> PS: If you want to create `PV` manually for `redis` or `postgresql`, please look into `existingClaim` in `.Values.yaml`

I manually created a PV, bound it to a PVC, and the pods are running. However, it keeps attempting to create new replicas for my-release-redis. Even after I delete them, new replicas are created.
<img width="908" alt="image" src="https://github.com/BorisPolonsky/dify-helm/assets/120240141/b57a5f5e-9ad7-4c41-9a5a-cf8243e4131c">
I feel like everything is fine now, but I cannot access the web page.

**Comment by YYyp99** [comment] 2024-02-26 09:33
> @YYyp99 So you've manually created a `PersistentVolume` named `dify-postgresql-primary` in namespace `default` which is claimed by `redis-data-my-release-redis-master-0`. This suggests that:
> 
> * The dynamic provisioning feature works fine, which rules out possible causes as `bitnami` described [here](https://docs.bitnami.com/kubernetes/faq/troubleshooting/troubleshooting-persistence-volumes/). (Component `redis` and `postgresql` are defined as dependency of [bitnami helm charts](https://github.com/bitnami/charts).)
> * [bitnami/redis](https://github.com/bitnami/charts/tree/main/bitnami/redis/templates) failed to create a `PersistentVolume` as expected with your setup, and its `PVC` claims your manually created `PV` that were meant for `postgresql` with storage class `NFS`, which is not ideal for `redis`. You may need to specify storage class explicitly to prevent such cases.  (e.g. `.Values.redis.master.persistence.storageClass`, `.Values.redis.replica.persistence.storageClass`, `api.persistence.persistentVolumeClaim.storageClass`)
> 
> We may need a copy of your `values.yaml` (without actual credential data) and your start up command to identify the cause of two issues
> 
> * no `PersistentVolume` were created by this chart or `bitnami` depdendency
> * `PVC` claims unexpected `PV`(wrong `PV` instance + wrong storage class)
> 
> PS: If you want to create `PV` manually for `redis` or `postgresql`, please look into `existingClaim` in `.Values.yaml`

I successfully created PVs and PVCs on my own, and all pods are in the running state.
<img width="682" alt="image" src="https://github.com/BorisPolonsky/dify-helm/assets/120240141/3de7b4dc-fe09-4036-8bb3-e137deb7afe1">
However, when I try to use the web service and execute kubectl port-forward service/my-release-dify-web 8888:3000, I cannot access it in the browser. When I use curl on the server, I encounter an error.
<img width="1251" alt="image" src="https://github.com/BorisPolonsky/dify-helm/assets/120240141/672d6671-5e5f-4841-a485-5cf98166ccbe">

**Comment by BorisPolonsky** [comment] 2024-02-26 09:50
@YYyp99 

AFAIK there's no such `service` forwarding mechanism. One could only forward from host to specific `pod`. 
The last few line from `stdout` upon `helm install` should demonstrate how one would achieve it.

We still need a copy of `values.yaml` in order to replicate this issue. Or we shall conclude that it's not a bug but user end configuration error.

**Comment by YYyp99** [comment] 2024-03-04 06:38
> @YYyp99
> 
> AFAIK there's no such `service` forwarding mechanism. One could only forward connections to specific `pod`. The last few line from `stdout` upon `helm install` should demonstrate how one would achieve it.
> 
> We still need a copy of `values.yaml` in order to replicate this issue. Or we shall conclude that it's not a bug but a user end configuration error.

Thank you very much. The version of dify you provided is 0.4.9. Is there a Helm Chart available for the latest version of dify, version 0.5.7?

**Comment by YYyp99** [comment] 2024-03-04 09:10
> image in `.Values.yaml`

I haven't used it yet. What I mean is, if I want to use version 0.5.7, do I just need to change the version of the image in Values. yaml, and the remaining configuration doesn't need to be changed

**Comment by BorisPolonsky** [comment] 2024-03-04 09:56
> > image in `.Values.yaml`
> 
> I haven't used it yet. What I mean is, if I want to use version 0.5.7, do I just need to change the version of the image in Values. yaml, and the remaining configuration doesn't need to be changed

This chart allows you to substitute images with these config defined in `.Values` in case you are in an environment without access to docker hub and need to pull image from another registry. We haven't test this chart in 0.5.x yet but we haven't seen any breaking change in official `dify` release note. You may have a try in non production environment first.

**Comment by BorisPolonsky** [comment] 2024-03-04 12:12
> @YYyp99
> 
> AFAIK there's no such `service` forwarding mechanism. One could only forward connections to specific `pod`. The last few line from `stdout` upon `helm install` should demonstrate how one would achieve it.
> 
> We still need a copy of `values.yaml` in order to replicate this issue. Or we shall conclude that it's not a bug but a user end configuration error.

@YYyp99 Since no `.Values.yaml` were provided and we could not replicate this issue, we shall conclude that it's a user end configuration error. Closing this issue.

**Closed by BorisPolonsky** 2024-03-04 12:12 UTC
Labels: bug
