### ISSUE TITLE
Deployment encountered an error, suspecting it's due to version issues.

### ISSUE THREAD

**Issue by HuangGuSheng** [BorisPolonsky/dify-helm#16] opened 2023-10-13 07:03 UTC
What are the requirements for Helm version and Kubernetes version? I attempted to deploy, but encountered an error, suspecting it might be a version issue.

error:
`Error: template: dify/templates/worker-config.yaml:6:6: executing "dify/templates/worker-config.yaml" at <include "dify.worker.config" .>: error calling include: template: dify/templates/config.tpl:97:4: executing "dify.worker.config" at <include "dify.vectordb.config" .>: error calling include: template: dify/templates/config.tpl:231:40: executing "dify.vectordb.config" at <eq .clusterIP "None">: error calling eq: incompatible types for comparison`

**Comment by BorisPolonsky** [comment] 2023-10-15 13:44
A possible duplicate of #6

**Closed** 2023-11-08 00:04 UTC
Labels: duplicate
